---
include:
  - board: eyelash_corne_left
    shield: kyria_left nice_view_adapter nice_view_gem #updated entry
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: kyria_right nice_view_adapter nice_view_gem #updated entry
 
